version: '2.39.3'
services:
    vprodb:
      build:
          context: ./Docker-file/db
      image: farespro/vprofiledb
      container_name: vprodb
      ports:
          - "3306:3306"
      volumes:
        - vprodbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD="vprodbpass"
      
    vprocache01:
      image: memcached
      container_name: vprocache01
      ports:
        -"11211:11211"


    vpromq01:
      image: rabbitmq
      container_name: vpromq01
      ports:
        - "5672:5672"
      environment:
        - RABBITMQ_DEFAULT_USER= guest
        - RABBITMQ_DEFAULT_PASS= guest

    vproapp:
      build:args:
        context: ./Docker-file/app
      image: farespro/vprofileapp
      container_name: vproapp
      ports:
        "8080:8080"
      volumes:
        - vproappdata:/usr/local/tomcat/webapps/
      
volumes:
  vprodbdata: {}
  vproappdata: {}